### ISSUE TITLE
Error: AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by chingor13** [googleapis/synthtool#683]
```
python3 -m synthtool
Traceback (most recent call last):
  File "/home/chingor/.asdf/installs/python/3.6.10/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chingor/.asdf/installs/python/3.6.10/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chingor/code/synthtool/synthtool/__main__.py", line 23, in <module>
    import synthtool.metadata
  File "/home/chingor/code/synthtool/synthtool/metadata.py", line 31, in <module>
    from synthtool.protos import metadata_pb2
  File "/home/chingor/code/synthtool/synthtool/protos/metadata_pb2.py", line 23, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

#### Environment details

  - OS: ubuntu
  - Python version: 3.6.10
  - pip version: 18.1
  - `synthtool` version: HEAD @ 529ee7c9a61fa02f4f158ff7f0288990d64ac0fe

#### Steps to reproduce

  1. Go to a java repo
  2. `python3 -m synthtool`

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by chingor13** [comment]
Looks like python 3.10 fixes this?

**Comment by chingor13** [comment]
Actually it seems I have an older version of protobuf that is incompatible with the latest changes. We should update the protobuf dependency in setup.py so that pip knows it needs to upgrade

**Comment by SurferJeffAtGoogle** [comment]
Done.

**Comment by skuruppu** [comment]
I installed synthtool today at HEAD (4530cc6ff080ef8aca258c1ec92c4db10a1bbfb4) but still getting this error.

  - OS: Debian 5.6.14
  - Python version: Python 3.8.4rc1
  - pip version: pip 20.0.2
  - `synthtool` version: HEAD (4530cc6ff080ef8aca258c1ec92c4db10a1bbfb4)

Should I change something about my setup?

**Comment by skuruppu** [comment]
Never mind, just had to do a `pip3 install protobuf --upgrade`. Thanks @larkee for the help.
